-- EMP-NNNN numbers are generated by counting the TENANT's own employees, so
-- every workspace starts at EMP-0001. A global unique index therefore made the
-- first hire of every new company collide with whichever unrelated tenant
-- already held EMP-0001 — the number is per-company, and the constraint has to
-- say so.
DROP INDEX "Employee_employeeNumber_key";

CREATE UNIQUE INDEX "Employee_companyId_employeeNumber_key"
  ON "Employee"("companyId", "employeeNumber");
